version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`
      - ./gradlew clean build
artifacts:
  files:
    - build/farm-water-delivery.jar